server:
  port: 8081
  error:
    include-message: always

spring:
  flyway:
    enabled: true
    baseline-version: 1
    locations:
      - classpath:db/migration
    sql-migration-suffixes: .sql
    baseline-on-migrate: true
    sql-migration-prefix: V
    schemas:
      - public

  datasource:
    url: jdbc:postgresql://ep-wandering-hall-a8p6ui8a-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_CYJk7GfN8Drg
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
