server:
  port: 8081
  error:
    include-message: always

spring:
  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    schemas:
      - public

  datasource:
    url: jdbc:postgresql://ep-nameless-violet-a8b7l2d6-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_xPIO2ebq3zYM
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.security: DEBUG
    com.example.Aplicativo_web: DEBUG